version: "3"
services:
  node-install:
    build:
      dockerfile: Dockerfile-install
      context: ./angular4
    image: alexsimons/nodeinstall:9.2.0
    volumes:
      - ./angular4:/app

#runs the node install